/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edd.gui;

import edd.estructuras.Data;
import edd.estructuras.Graficar;
import edd.estructuras.ListaDatos;
import edd.estructuras.Manejador;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Saul
 */
public class Loads extends javax.swing.JFrame {

    /**
     * Creates new form Loads
     */
    public Loads() {
        initComponents();
        ListaDatos.getInstancia().cargarDatos();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lblItem = new javax.swing.JLabel();
        lblPersonaje = new javax.swing.JLabel();
        btnAgrega = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAcepta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnFinish = new javax.swing.JButton();
        cbLista = new javax.swing.JComboBox();
        cbElegidos = new javax.swing.JComboBox();
        btnEditar = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mario.png"))); // NOI18N
        getContentPane().add(lblItem);
        lblItem.setBounds(70, 40, 48, 48);
        getContentPane().add(lblPersonaje);
        lblPersonaje.setBounds(370, 40, 48, 48);

        btnAgrega.setText("ELEGIR");
        btnAgrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgrega);
        btnAgrega.setBounds(197, 123, 90, 30);

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 110, 60, 14);

        txtNombre.setEnabled(false);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(360, 130, 80, 25);

        btnAcepta.setText("ACEPTAR");
        btnAcepta.setEnabled(false);
        btnAcepta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcepta);
        btnAcepta.setBounds(200, 223, 90, 30);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setEnabled(false);
        jScrollPane1.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 154, 160, 120);
        getContentPane().add(txtCantidad);
        txtCantidad.setBounds(360, 190, 80, 25);

        jLabel5.setText("Cantidad");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 170, 50, 14);

        btnFinish.setText("FINALIZAR");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinish);
        btnFinish.setBounds(363, 263, 120, 30);

        cbLista.setModel(combo);
        cbLista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbListaItemStateChanged(evt);
            }
        });
        getContentPane().add(cbLista);
        cbLista.setBounds(40, 110, 110, 20);

        cbElegidos.setModel(combo2);
        cbElegidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbElegidosItemStateChanged(evt);
            }
        });
        getContentPane().add(cbElegidos);
        cbElegidos.setBounds(190, 40, 110, 20);

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(189, 70, 110, 23);

        btnSave.setText("Guardar");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(401, 230, 80, 23);

        setSize(new java.awt.Dimension(509, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        new Principal().setVisible(true);
        Graficar graficas = new Graficar();
        graficas.graficaLista();
        dispose();
    }//GEN-LAST:event_btnFinishActionPerformed

    private void cbListaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbListaItemStateChanged
        for(Data elemento:ListaDatos.getInstancia().getLista()){
            if(cbLista.getSelectedItem().equals(elemento.getPersonaje())){
                txtDescripcion.setText("");
                txtDescripcion.append(elemento.getPersonaje() + "\n");
                txtDescripcion.append(elemento.getDescripcion() + "\n");
                txtDescripcion.append(elemento.getTipo());
                lblItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + elemento.getImagen())));
            }
        }
    }//GEN-LAST:event_cbListaItemStateChanged

    private void btnAgregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaActionPerformed
        btnAcepta.setEnabled(true);
        if(cbLista.getSelectedItem().equals("MarioBross")){
            txtNombre.setEnabled(true);
            txtCantidad.setText("1");
            txtCantidad.setEnabled(false);
        }else{
            txtNombre.setEnabled(false);
            txtNombre.setText("");
            txtCantidad.setText("");
            txtCantidad.setEnabled(true);
        }
        Data dato = ListaDatos.getInstancia().getDatos(cbLista.getSelectedItem().toString());
        lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + dato.getImagen())));
    }//GEN-LAST:event_btnAgregaActionPerformed

    private void btnAceptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptaActionPerformed
        if(!txtCantidad.getText().trim().equals("")){
            btnAcepta.setEnabled(false);
            Data dato = ListaDatos.getInstancia().getDatos(cbLista.getSelectedItem().toString());
            if(!txtNombre.getText().equals(""))dato.setNombre(txtNombre.getText());
            dato.setCantidad(Integer.parseInt(txtCantidad.getText()));
            Manejador.getInstancia().insert(dato);
            combo2.addElement(cbLista.getSelectedItem());
            //ListaDatos.getInstancia().getLista().remove(dato);
            combo.removeElement(cbLista.getSelectedItem());
            limpiar();
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "Favor no dejar Cantida en blanco.");
        }
        
    }//GEN-LAST:event_btnAceptaActionPerformed

    private void cbElegidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbElegidosItemStateChanged

    }//GEN-LAST:event_cbElegidosItemStateChanged
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        btnAcepta.setEnabled(false);
        btnSave.setEnabled(true);
        for(Data elemento:ListaDatos.getInstancia().getLista()){
            if(cbElegidos.getSelectedItem().equals(elemento.getPersonaje())){
                System.out.println("Personaje: " + elemento.getPersonaje());
                if(elemento.getPersonaje().equals("MarioBross")){
                    txtNombre.setEnabled(true);
                    txtNombre.setText(Manejador.getInstancia().buscar(elemento.getPersonaje()).getNombre());
                    txtCantidad.setEnabled(false);
                }else{
                    txtNombre.setEnabled(false);
                    txtCantidad.setEnabled(true);
                    txtNombre.setText("");
                }
                txtCantidad.setText(String.valueOf(Manejador.getInstancia().buscar(elemento.getPersonaje()).getCantidad()));
                lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + elemento.getImagen())));
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Data elemento = Manejador.getInstancia().buscar(cbElegidos.getSelectedItem().toString());
        elemento.setNombre(txtNombre.getText());
        elemento.setCantidad(Integer.parseInt(txtCantidad.getText()));
        limpiar();
        btnSave.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    private void limpiar(){
        txtNombre.setText("");
        txtCantidad.setText("");
        lblPersonaje.setIcon(null);
    }
    
    private void cargarDatos(){
        for(Data datos:ListaDatos.getInstancia().getLista()){
            combo.addElement(datos.getPersonaje());
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loads().setVisible(true);
            }
        });
    }
    DefaultComboBoxModel combo = new DefaultComboBoxModel();
    DefaultComboBoxModel combo2 = new DefaultComboBoxModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcepta;
    private javax.swing.JButton btnAgrega;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbElegidos;
    private javax.swing.JComboBox cbLista;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblPersonaje;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
