/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edd.gui;

import edd.estructuras.Manejador;
import edd.estructuras.NodoDoble;
import java.awt.Rectangle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JLabel;

/**
 *
 * @author Saul
 */
public class Make extends javax.swing.JFrame {

    /**
     * Creates new form Make
     */
    public Make() {
        initComponents();
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPersonaje = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        pnlMake = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRestantes = new javax.swing.JTextField();
        btnFila = new javax.swing.JButton();
        btnColumna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/castillo.png"))); // NOI18N
        lblPersonaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPersonajeMouseClicked(evt);
            }
        });
        getContentPane().add(lblPersonaje);
        lblPersonaje.setBounds(310, 20, 48, 48);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente);
        btnSiguiente.setBounds(190, 20, 100, 23);

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnterior);
        btnAnterior.setBounds(190, 50, 100, 23);

        pnlMake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlMake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMakeMouseClicked(evt);
            }
        });
        pnlMake.setLayout(null);
        getContentPane().add(pnlMake);
        pnlMake.setBounds(20, 90, 192, 96);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(450, 20, 80, 23);

        jLabel1.setText("Restantes:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 20, 65, 14);

        txtRestantes.setEnabled(false);
        getContentPane().add(txtRestantes);
        txtRestantes.setBounds(380, 40, 50, 20);

        btnFila.setText("FILA +");
        btnFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFila);
        btnFila.setBounds(20, 20, 120, 23);

        btnColumna.setText("COLUMNA +");
        btnColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColumnaActionPerformed(evt);
            }
        });
        getContentPane().add(btnColumna);
        btnColumna.setBounds(20, 50, 120, 23);

        setSize(new java.awt.Dimension(561, 239));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private Icon icono;
    private void lblPersonajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonajeMouseClicked
        icono = lblPersonaje.getIcon();   
    }//GEN-LAST:event_lblPersonajeMouseClicked

    private void pnlMakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMakeMouseClicked
        System.out.println("En x = " + pnlMake.getMousePosition().x);
        int z = pnlMake.getWidth() / 48;
        for(int i = 0; i<z; i++){
            int x = pnlMake.getMousePosition().x;
            if(x >= (i*48) && x <=((i+1)*48)){
                System.out.println("Que con posicion x = " + i*48);
                int w =  pnlMake.getHeight() / 48;
                int y = pnlMake.getMousePosition().y;
                for(int j = 0; j<w; j++){
                    if(y >= (j * 48) && y<= ((j + 1) * 48)){
                        System.out.println("Posicion en y = " + j * 48);
                        JLabel nuevo = new JLabel();
                        nuevo.setIcon(icono);
                        nuevo.setBounds(i*48, j*48, 48, 48);
                        pnlMake.add(nuevo);
                        pnlMake.repaint();
                        aux.getDatos().setCantidad(aux.getDatos().getCantidad() - 1);
                    }
                }
            }
        }
    }//GEN-LAST:event_pnlMakeMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Principal().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if(aux.getSiguiente() != null){
            aux = aux.getSiguiente();
            lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + aux.getDatos().getImagen())));
            txtRestantes.setText(String.valueOf(aux.getDatos().getCantidad()));
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if(aux.getAnterior() != null){
            aux = aux.getAnterior();
            lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + aux.getDatos().getImagen())));
            txtRestantes.setText(String.valueOf(aux.getDatos().getCantidad()));
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilaActionPerformed
        pnlMake.setBounds(pnlMake.getX(), pnlMake.getY(), pnlMake.getWidth(), pnlMake.getHeight() + 48);
        
    }//GEN-LAST:event_btnFilaActionPerformed

    private void btnColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColumnaActionPerformed
        pnlMake.setBounds(pnlMake.getX(), pnlMake.getY(), pnlMake.getWidth() + 48, pnlMake.getHeight());
    }//GEN-LAST:event_btnColumnaActionPerformed
    private void cargar(){
        aux = Manejador.getInstancia().listaElementos.getPrimero();
        lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + aux.getDatos().getImagen())));
        txtRestantes.setText(String.valueOf(aux.getDatos().getCantidad()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Make.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Make.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Make.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Make.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Make().setVisible(true);
            }
        });
    }
    private NodoDoble aux = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnColumna;
    private javax.swing.JButton btnFila;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPersonaje;
    private javax.swing.JPanel pnlMake;
    private javax.swing.JTextField txtRestantes;
    // End of variables declaration//GEN-END:variables
}
